/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BerandaRouteImport } from './routes/beranda'
import { Route as LombaRouteImport } from './routes/lomba'
import { Route as RundownRouteImport } from './routes/rundown'
import { Route as TimRouteImport } from './routes/tim'
import { Route as LombaIndexRouteImport } from './routes/lomba/index'
import { Route as LombaIdRouteImport } from './routes/lomba/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BerandaRoute = BerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => rootRouteImport,
} as any)
const LombaRoute = LombaRouteImport.update({
  id: '/lomba',
  path: '/lomba',
  getParentRoute: () => rootRouteImport,
} as any)
const RundownRoute = RundownRouteImport.update({
  id: '/rundown',
  path: '/rundown',
  getParentRoute: () => rootRouteImport,
} as any)
const TimRoute = TimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => rootRouteImport,
} as any)
const LombaIndexRoute = LombaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LombaRoute,
} as any)
const LombaIdRoute = LombaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LombaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/lomba': typeof LombaRouteWithChildren
  '/rundown': typeof RundownRoute
  '/tim': typeof TimRoute
  '/lomba/$id': typeof LombaIdRoute
  '/lomba/': typeof LombaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/rundown': typeof RundownRoute
  '/tim': typeof TimRoute
  '/lomba/$id': typeof LombaIdRoute
  '/lomba': typeof LombaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/lomba': typeof LombaRouteWithChildren
  '/rundown': typeof RundownRoute
  '/tim': typeof TimRoute
  '/lomba/$id': typeof LombaIdRoute
  '/lomba/': typeof LombaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/beranda' | '/lomba' | '/rundown' | '/tim' | '/lomba/$id' | '/lomba/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/beranda' | '/rundown' | '/tim' | '/lomba/$id' | '/lomba'
  id:
    | '__root__'
    | '/'
    | '/beranda'
    | '/lomba'
    | '/rundown'
    | '/tim'
    | '/lomba/$id'
    | '/lomba/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BerandaRoute: typeof BerandaRoute
  LombaRoute: typeof LombaRouteWithChildren
  RundownRoute: typeof RundownRoute
  TimRoute: typeof TimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beranda': {
      id: '/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof BerandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lomba': {
      id: '/lomba'
      path: '/lomba'
      fullPath: '/lomba'
      preLoaderRoute: typeof LombaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rundown': {
      id: '/rundown'
      path: '/rundown'
      fullPath: '/rundown'
      preLoaderRoute: typeof RundownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim': {
      id: '/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof TimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lomba/': {
      id: '/lomba/'
      path: '/'
      fullPath: '/lomba/'
      preLoaderRoute: typeof LombaIndexRouteImport
      parentRoute: typeof LombaRoute
    }
    '/lomba/$id': {
      id: '/lomba/$id'
      path: '/$id'
      fullPath: '/lomba/$id'
      preLoaderRoute: typeof LombaIdRouteImport
      parentRoute: typeof LombaRoute
    }
  }
}

interface LombaRouteChildren {
  LombaIdRoute: typeof LombaIdRoute
  LombaIndexRoute: typeof LombaIndexRoute
}

const LombaRouteChildren: LombaRouteChildren = {
  LombaIdRoute: LombaIdRoute,
  LombaIndexRoute: LombaIndexRoute,
}

const LombaRouteWithChildren = LombaRoute._addFileChildren(LombaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BerandaRoute: BerandaRoute,
  LombaRoute: LombaRouteWithChildren,
  RundownRoute: RundownRoute,
  TimRoute: TimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
